import type { RoleDef, RoleId } from './types'

/**
 * Configuration de tous les rôles. Ajouter un rôle = ajouter une entrée ici.
 * Les écrans et le moteur ne connaissent les rôles qu'à travers cette liste.
 */
export const ROLES: RoleDef[] = [
  {
    id: 'soeur',
    nom: 'Sœurs',
    emoji: '👭',
    camp: 'village',
    frequence: 'premiere_nuit',
    ordre: 10,
    phrase_reveil: 'Les Sœurs, réveillez-vous et reconnaissez-vous en silence.',
    phrase_coucher: 'Les Sœurs, rendormez-vous.',
    actions: [],
    effets: [],
    description_courte: 'Villageoises qui se connaissent entre elles : elles savent qu’elles peuvent se faire confiance.',
    quantites: { max: 3, permises: [2, 3] },
  },
  {
    id: 'frere',
    nom: 'Frères',
    emoji: '👬',
    camp: 'village',
    frequence: 'premiere_nuit',
    ordre: 11,
    phrase_reveil: 'Les trois Frères, réveillez-vous et reconnaissez-vous en silence.',
    phrase_coucher: 'Les Frères, rendormez-vous.',
    actions: [],
    effets: [],
    description_courte: 'Trois villageois qui se connaissent entre eux.',
    quantites: { max: 3, permises: [3] },
  },
  {
    id: 'cupidon',
    nom: 'Cupidon',
    emoji: '💘',
    camp: 'village',
    frequence: 'premiere_nuit',
    ordre: 20,
    phrase_reveil: 'Cupidon, réveille-toi. Désigne les deux joueurs qui tomberont éperdument amoureux.',
    phrase_coucher: 'Cupidon, rendors-toi.',
    actions: [
      { id: 'amoureux', type: 'joueurs', libelle: 'Les 2 Amoureux', effet: 'amour', nombre: 2, contraintes: ['vivant'] },
    ],
    effets: [],
    description_courte: 'Unit deux joueurs (il peut se choisir). Si l’un meurt, l’autre meurt de chagrin.',
    quantites: { max: 1 },
    compagnon: {
      id: 'amoureux',
      nom: 'Amoureux',
      emoji: '❤️',
      phrase_reveil:
        'Je vais toucher la tête des deux Amoureux… Amoureux, réveillez-vous et reconnaissez-vous. Si l’un de vous meurt, l’autre mourra de chagrin.',
      phrase_coucher: 'Amoureux, rendormez-vous.',
      description_courte:
        'Touche la tête des deux Amoureux, laisse-les se reconnaître. S’ils sont de camps différents, ils gagnent ensemble s’ils sont les derniers survivants.',
    },
  },
  {
    id: 'infect_pere',
    nom: 'Infect Père des Loups',
    emoji: '🧪',
    camp: 'loups',
    estLoup: true,
    frequence: 'premiere_nuit',
    ordre: 30,
    phrase_reveil: 'Infect Père des Loups, réveille-toi et montre-toi à moi.',
    phrase_coucher: 'Infect Père des Loups, rendors-toi.',
    actions: [],
    effets: [],
    description_courte:
      'Loup-garou. Une fois par partie, il peut infecter la victime des loups au lieu de la tuer : elle devient loup en secret.',
    quantites: { max: 1 },
  },
  {
    id: 'enfant_sauvage',
    nom: 'Enfant sauvage',
    emoji: '🧒',
    camp: 'village',
    frequence: 'premiere_nuit',
    ordre: 40,
    phrase_reveil: 'Enfant sauvage, réveille-toi. Désigne le joueur qui sera ton modèle.',
    phrase_coucher: 'Enfant sauvage, rendors-toi.',
    actions: [
      {
        id: 'modele',
        type: 'joueurs',
        libelle: 'Son modèle',
        effet: 'modele',
        nombre: 1,
        contraintes: ['vivant', 'pas_soi_meme'],
      },
    ],
    effets: ['devient_loup_si_modele_meurt'],
    description_courte: 'Villageois tant que son modèle est en vie. Si le modèle meurt, il devient Loup-Garou.',
    quantites: { max: 1 },
  },
  {
    id: 'chien_loup',
    nom: 'Chien-loup',
    emoji: '🐕',
    camp: 'ambigu',
    frequence: 'premiere_nuit',
    ordre: 45,
    phrase_reveil: 'Chien-loup, réveille-toi. Choisis ton camp : fidèle chien du village, ou loup sauvage ?',
    phrase_coucher: 'Chien-loup, rendors-toi.',
    actions: [
      {
        id: 'camp',
        type: 'choix',
        libelle: 'Camp choisi',
        effet: 'camp_chien_loup',
        options: [
          { valeur: 'village', libelle: '🐕 Village' },
          { valeur: 'loups', libelle: '🐺 Loups-Garous' },
        ],
      },
    ],
    effets: [],
    description_courte: 'Choisit son camp la première nuit. S’il choisit les loups, il se réveille avec eux dès cette nuit.',
    quantites: { max: 1 },
  },
  {
    id: 'ange',
    nom: 'Ange',
    emoji: '😇',
    camp: 'solo',
    frequence: 'premiere_nuit',
    ordre: 50,
    phrase_reveil: 'Ange, réveille-toi et montre-toi à moi.',
    phrase_coucher: 'Ange, rendors-toi.',
    actions: [],
    effets: ['gagne_si_elimine_premier_vote'],
    description_courte:
      'Gagne seul s’il est éliminé au tout premier vote du village. Sinon, il devient un simple villageois.',
    quantites: { max: 1 },
  },
  {
    id: 'montreur_ours',
    nom: 'Montreur d’ours',
    emoji: '🐻',
    camp: 'village',
    frequence: 'premiere_nuit',
    ordre: 55,
    phrase_reveil: 'Montreur d’ours, réveille-toi et montre-toi à moi.',
    phrase_coucher: 'Montreur d’ours, rendors-toi.',
    actions: [],
    effets: ['grognement_ours'],
    description_courte:
      'Pas d’action la nuit. Chaque matin, son ours grogne si un de ses voisins vivants est un loup. L’app te le dira.',
    quantites: { max: 1 },
    requiertCercle: true,
  },
  {
    id: 'chasseur',
    nom: 'Chasseur',
    emoji: '🏹',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 60,
    phrase_reveil: 'Chasseur, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Chasseur, rendors-toi.',
    actions: [],
    effets: ['tir_a_la_mort'],
    description_courte: 'Quand il meurt, il tire immédiatement sur un joueur de son choix, qui meurt aussi.',
    quantites: { max: 1 },
  },
  {
    id: 'ancien',
    nom: 'Ancien',
    emoji: '👴',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 61,
    phrase_reveil: 'Ancien, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Ancien, rendors-toi.',
    actions: [],
    effets: ['survit_premiere_attaque'],
    description_courte:
      'Survit à la première attaque des loups. S’il est tué par le village (vote, Sorcière, Chasseur), les villageois perdent leurs pouvoirs.',
    quantites: { max: 1 },
  },
  {
    id: 'idiot',
    nom: 'Idiot du village',
    emoji: '🤪',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 62,
    phrase_reveil: 'Idiot du village, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Idiot du village, rendors-toi.',
    actions: [],
    effets: ['gracie_au_vote'],
    description_courte: 'S’il est désigné par le vote, il est gracié : il révèle sa carte, reste en vie mais ne vote plus.',
    quantites: { max: 1 },
  },
  {
    id: 'chevalier',
    nom: 'Chevalier à l’épée rouillée',
    emoji: '🗡️',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 63,
    phrase_reveil: 'Chevalier, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Chevalier, rendors-toi.',
    actions: [],
    effets: ['tetanos'],
    description_courte:
      'S’il est dévoré par les loups, le premier loup à sa gauche attrape le tétanos et meurt la nuit suivante.',
    quantites: { max: 1 },
  },
  {
    id: 'bouc_emissaire',
    nom: 'Bouc émissaire',
    emoji: '🐐',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 64,
    phrase_reveil: 'Bouc émissaire, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Bouc émissaire, rendors-toi.',
    actions: [],
    effets: ['elimine_si_egalite'],
    description_courte: 'En cas d’égalité au vote, c’est lui qui est éliminé à la place des autres.',
    quantites: { max: 1 },
  },
  {
    id: 'servante',
    nom: 'Servante dévouée',
    emoji: '🧹',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 65,
    phrase_reveil: 'Servante dévouée, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Servante dévouée, rendors-toi.',
    actions: [],
    effets: ['prend_role_elimine'],
    description_courte:
      'Quand un joueur est éliminé par le vote, elle peut se révéler avant qu’il montre sa carte et prendre son rôle.',
    quantites: { max: 1 },
  },
  {
    id: 'petite_fille',
    nom: 'Petite fille',
    emoji: '👧',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    identificationNuit1: true,
    ordre: 66,
    phrase_reveil: 'Petite fille, réveille-toi et montre-toi discrètement à moi.',
    phrase_coucher: 'Petite fille, rendors-toi.',
    actions: [],
    effets: [],
    description_courte:
      'Peut entrouvrir les yeux pendant le tour des loups pour les espionner. Si les loups la surprennent, ils peuvent la choisir.',
    quantites: { max: 1 },
  },
  {
    id: 'renard',
    nom: 'Renard',
    emoji: '🦊',
    camp: 'village',
    frequence: 'chaque_nuit',
    ordre: 100,
    phrase_reveil: 'Renard, réveille-toi. Désigne un joueur : je te dirai si lui ou l’un de ses voisins est un loup.',
    phrase_coucher: 'Renard, rendors-toi.',
    actions: [{ id: 'cible', type: 'joueurs', libelle: 'Joueur flairé', effet: 'flair', nombre: 1, contraintes: ['vivant'] }],
    effets: ['perd_pouvoir_si_non'],
    description_courte:
      'Flaire un groupe de 3 (le joueur et ses 2 voisins vivants). S’il n’y a aucun loup, il perd définitivement son pouvoir.',
    quantites: { max: 1 },
    requiertCercle: true,
  },
  {
    id: 'salvateur',
    nom: 'Salvateur',
    emoji: '🛡️',
    camp: 'village',
    frequence: 'chaque_nuit',
    ordre: 110,
    phrase_reveil: 'Salvateur, réveille-toi. Désigne le joueur que tu veux protéger cette nuit.',
    phrase_coucher: 'Salvateur, rendors-toi.',
    actions: [
      {
        id: 'protege',
        type: 'joueurs',
        libelle: 'Joueur protégé',
        effet: 'protection',
        nombre: 1,
        contraintes: ['vivant', 'pas_meme_que_nuit_precedente'],
      },
    ],
    effets: [],
    description_courte:
      'Protège un joueur de l’attaque des loups. Il peut se protéger lui-même, mais jamais le même joueur deux nuits de suite.',
    quantites: { max: 1 },
  },
  {
    id: 'voyante',
    nom: 'Voyante',
    emoji: '🔮',
    camp: 'village',
    frequence: 'chaque_nuit',
    ordre: 120,
    phrase_reveil: 'Voyante, réveille-toi. Désigne le joueur dont tu veux connaître l’identité.',
    phrase_coucher: 'Voyante, rendors-toi.',
    actions: [
      {
        id: 'cible',
        type: 'joueurs',
        libelle: 'Joueur sondé',
        effet: 'voyance',
        nombre: 1,
        contraintes: ['vivant', 'pas_soi_meme'],
      },
    ],
    effets: [],
    description_courte: 'Découvre chaque nuit la carte d’un joueur. Montre-lui la carte (ou mime-la).',
    quantites: { max: 1 },
  },
  {
    id: 'corbeau',
    nom: 'Corbeau',
    emoji: '🐦‍⬛',
    camp: 'village',
    frequence: 'chaque_nuit',
    ordre: 130,
    phrase_reveil: 'Corbeau, réveille-toi. Désigne le joueur que tu veux accuser : il aura deux voix de plus contre lui demain.',
    phrase_coucher: 'Corbeau, rendors-toi.',
    actions: [
      {
        id: 'cible',
        type: 'joueurs',
        libelle: 'Joueur accusé (+2 voix)',
        effet: 'corbeau',
        nombre: 1,
        contraintes: ['vivant'],
        optionnel: true,
      },
    ],
    effets: [],
    description_courte: 'Le joueur désigné commence le prochain vote avec 2 voix contre lui.',
    quantites: { max: 1 },
  },
  {
    id: 'loup_garou',
    nom: 'Loups-Garous',
    emoji: '🐺',
    camp: 'loups',
    estLoup: true,
    reveilAvecLoups: true,
    meute: true,
    frequence: 'chaque_nuit',
    ordre: 140,
    phrase_reveil: 'Loups-Garous, réveillez-vous. Mettez-vous d’accord en silence et désignez votre victime.',
    phrase_coucher: 'Loups-Garous, rendormez-vous.',
    actions: [
      {
        id: 'victime',
        type: 'joueurs',
        libelle: 'Victime des loups',
        effet: 'attaque_loups',
        nombre: 1,
        contraintes: ['vivant', 'pas_loup'],
        optionnel: true,
      },
      {
        id: 'infection',
        type: 'oui_non',
        libelle: 'Infect Père : infecter au lieu de tuer ?',
        effet: 'infection',
        disponibleSi: 'infection_disponible',
        dependDe: 'victime',
      },
    ],
    effets: [],
    description_courte:
      'Toute la meute se réveille (Infect Père et loups convertis compris) et choisit une victime à dévorer.',
    quantites: { max: 12 },
  },
  {
    id: 'grand_mechant_loup',
    nom: 'Grand Méchant Loup',
    emoji: '🐺',
    camp: 'loups',
    estLoup: true,
    reveilAvecLoups: true,
    frequence: 'chaque_nuit',
    ordre: 150,
    phrase_reveil: 'Grand Méchant Loup, reste éveillé. Désigne une seconde victime.',
    phrase_coucher: 'Grand Méchant Loup, rendors-toi.',
    actions: [
      {
        id: 'victime',
        type: 'joueurs',
        libelle: 'Seconde victime',
        effet: 'attaque_grand_mechant_loup',
        nombre: 1,
        contraintes: ['vivant', 'pas_loup', 'pas_victime_loups'],
        optionnel: true,
        disponibleSi: 'grand_mechant_loup_actif',
      },
    ],
    effets: ['actif_tant_qu_aucun_loup_mort'],
    description_courte: 'Tant qu’aucun loup n’est mort, il dévore une seconde victime chaque nuit.',
    quantites: { max: 1 },
  },
  {
    id: 'loup_blanc',
    nom: 'Loup Blanc',
    emoji: '🤍',
    camp: 'solo',
    estLoup: true,
    reveilAvecLoups: true,
    frequence: 'une_nuit_sur_deux',
    ordre: 160,
    phrase_reveil: 'Loup Blanc, reste éveillé. Si tu le souhaites, désigne un loup à dévorer.',
    phrase_coucher: 'Loup Blanc, rendors-toi.',
    actions: [
      {
        id: 'victime',
        type: 'joueurs',
        libelle: 'Loup dévoré',
        effet: 'attaque_loup_blanc',
        nombre: 1,
        contraintes: ['vivant', 'loup', 'pas_soi_meme'],
        optionnel: true,
      },
    ],
    effets: ['gagne_seul'],
    description_courte: 'Se réveille avec les loups mais veut gagner seul. Une nuit sur deux, il peut tuer un loup.',
    quantites: { max: 1 },
  },
  {
    id: 'sorciere',
    nom: 'Sorcière',
    emoji: '🧙‍♀️',
    camp: 'village',
    frequence: 'chaque_nuit',
    ordre: 170,
    phrase_reveil:
      'Sorcière, réveille-toi. Voici la victime de cette nuit. Veux-tu utiliser ta potion de vie ? Ta potion de mort ?',
    phrase_coucher: 'Sorcière, rendors-toi.',
    actions: [
      {
        id: 'vie',
        type: 'joueurs',
        libelle: '🧪 Potion de vie : sauver',
        effet: 'potion_vie',
        nombre: 1,
        source: 'victimes_nuit',
        optionnel: true,
        disponibleSi: 'potion_vie',
      },
      {
        id: 'mort',
        type: 'joueurs',
        libelle: '☠️ Potion de mort : empoisonner',
        effet: 'potion_mort',
        nombre: 1,
        contraintes: ['vivant', 'pas_soi_meme'],
        optionnel: true,
        disponibleSi: 'potion_mort',
      },
    ],
    effets: [],
    description_courte: 'Une potion de vie et une potion de mort, chacune utilisable une seule fois dans la partie.',
    quantites: { max: 1 },
  },
  {
    id: 'joueur_flute',
    nom: 'Joueur de flûte',
    emoji: '🪈',
    camp: 'solo',
    frequence: 'chaque_nuit',
    ordre: 180,
    phrase_reveil: 'Joueur de flûte, réveille-toi. Désigne les deux joueurs que tu veux charmer.',
    phrase_coucher: 'Joueur de flûte, rendors-toi.',
    actions: [
      {
        id: 'charmes',
        type: 'joueurs',
        libelle: 'Joueurs charmés',
        effet: 'charme',
        nombre: 2,
        contraintes: ['vivant', 'pas_soi_meme', 'non_charme'],
      },
    ],
    effets: ['gagne_si_tous_charmes'],
    description_courte: 'Gagne seul si tous les autres joueurs vivants sont charmés.',
    quantites: { max: 1 },
    compagnon: {
      id: 'charmes',
      nom: 'Joueurs charmés',
      emoji: '🎶',
      phrase_reveil:
        'Je vais toucher la tête des nouveaux charmés… Joueurs charmés, réveillez-vous et reconnaissez-vous.',
      phrase_coucher: 'Joueurs charmés, rendormez-vous.',
      description_courte: 'Touche la tête des joueurs charmés cette nuit. Tous les charmés se réveillent ensemble.',
    },
  },
  {
    id: 'villageois',
    nom: 'Simple Villageois',
    emoji: '🧑‍🌾',
    camp: 'village',
    frequence: 'jamais_la_nuit',
    ordre: 999,
    phrase_reveil: '',
    phrase_coucher: '',
    actions: [],
    effets: [],
    description_courte: 'Aucun pouvoir, mais une voix précieuse au vote.',
    quantites: { max: 40 },
  },
]

export const VILLAGER_ID = 'villageois'

const BY_ID = new Map(ROLES.map((r) => [r.id, r]))

export function getRole(id: RoleId): RoleDef {
  const role = BY_ID.get(id)
  if (!role) throw new Error(`Rôle inconnu : ${id}`)
  return role
}

export function findRole(id: RoleId | null | undefined): RoleDef | undefined {
  return id ? BY_ID.get(id) : undefined
}

export function hasEffect(roleId: RoleId | null | undefined, effet: RoleDef['effets'][number]): boolean {
  return findRole(roleId)?.effets.includes(effet) ?? false
}

/** Rôles appelés la nuit (ou identifiés la nuit 1), triés par ordre par défaut. */
export function defaultOrder(): RoleId[] {
  return ROLES.filter((r) => r.id !== VILLAGER_ID && (r.frequence !== 'jamais_la_nuit' || r.identificationNuit1))
    .sort((a, b) => a.ordre - b.ordre)
    .map((r) => r.id)
}
